apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: luuphuong13/mysql:phuonglv
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Phuong@2000"
        - name: MYSQL_DATABASE
          value: "web"
        - name: MYSQL_USER
          value: "phuonglv"
        - name: MYSQL_PASSWORD
          value: "Phuong@2000"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-my
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

