apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: luuphuong13/php:phuonglv
        env:
        - name: DB_HOST
          value: "mysql-my"
        - name: DB_USER
          value: "phuonglv"
        - name: DB_PASSWORD
          value: "Phuong@2000"
        - name: DB_NAME
          value: "web"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

